kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route-frontend
  labels:
    app: todonodejs
  namespace: mysql
spec:
  host: prod-todo.apps.ocp4.example.com
  path: "/todo/"
  to:
    kind: Service
    name: prod-frontend
    weight: 100
